### ISSUE TITLE
It's not enabled by default.

### ISSUE THREAD

**Issue by nyngwang** [LiadOz/nvim-dap-repl-highlights#2]
I just tried your plugin but it has no effect, these are the related configs:

```lua
{
  'nvim-treesitter/nvim-treesitter',
  build = ':TSUpdate',
  dependencies = {
    -- many unrelated lines omitted.
    { 'LiadOz/nvim-dap-repl-highlights', config = true },
  },
  config = function ()
    -- I also tried the next line too, same result.
    -- require('nvim-dap-repl-highlights').setup()
    require('nvim-treesitter.configs').setup {
      -- many unrelated lines omitted.
      ensure_installed = { 'dap_repl' },
```

**Comment by MrPandey01** [comment]
I've the same problem. `TSInstallInfo` shows that 'dap_repl' is installed.

**Comment by LiadOz** [comment]
> I've the same problem. `TSInstallInfo` shows that 'dap_repl' is installed.
> 
> `:lua print(vim.treesitter.inspect_language('dap_repl'))` returns the table successfully.

@MrPandey01 Can you try again using the following branch `LiadOz/fix-check-parser` I have tried running with your configs and with this change it worked.

**Comment by MrPandey01** [comment]
Still doesn't work for me. Table is still returned successfully and `TSInstallInfo` still says that the parser is installed. Here is the link to my nvim config if you'd like to see other details https://github.com/MrPandey01/dotfiles/blob/89e8562235ee3f7eeeca497b308537fdb8debef1/.config/nvim/lua/plugins/dap/init.lua#L16

**Comment by LiadOz** [comment]
@MrPandey01 I think you installed the plugin with the branch wrong, can you try instead `{ 'LiadOz/nvim-dap-repl-highlights',  branch = 'LiadOz/fix-check-parser' }`, simply in the branch put a string instead of a table.

**Comment by LiadOz** [comment]
@nyngwang I believe the latest commit solves the issue, if it still happens on your config please reopen this issue.

**Comment by nyngwang** [comment]
Well, I don't think it is solved:

![image](https://github.com/LiadOz/nvim-dap-repl-highlights/assets/24765272/b72d150d-6d13-4f25-a3d8-f7a349f380ee)

my config:

![image](https://github.com/LiadOz/nvim-dap-repl-highlights/assets/24765272/3cebb4a8-0e3a-421a-a5a8-eecb6b97d5f5)

**Comment by LiadOz** [comment]
@nyngwang you may be missing the python treesitter parser, try to install it manually with `:TSInstall python` or by adding it the the ensure_installed.
If that doesn't can you paste the content of the `:messages` command?
